spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: goal-service
          uri: http://localhost:8095
          predicates:
            - Path=/goal/**
        - id: collaboration-service
          uri: http://localhost:8097
          predicates:
            - Path=/collab/**

server:
  port: 8222

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
