spring:
  application:
    name: goal-service
  datasource:
    url: jdbc:mysql://localhost:3306/GoalService?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8095
  servlet:
    context-path: /goal

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka